# This is a YAML file for configuring the correlator.

# To set the default log file and level for an EPL package, monitor, or event, specify
# logging details in the eplLogging section of the YAML configuration file.
# For example:
#   eplLogging:
#     com.myCompany.Client:
#       file: apama/Client.log
#       level: DEBUG
#     com.myCompany.Internal: { level: ERROR }

# See the information on setting log files and log levels in a YAML configuration file in the documentation for more
# information about the supported options.
